add sendMessage function
capacitor-community/fcm pull request #112
Opened 2022-06-12 19:01 UTC by bartacruz

2022-06-12 20:27 UTC, bartacruz commented
Sorry, I've updated my fork with an old testing version. That's why I've closed the PR.
Now it's ok.

2022-10-03 17:38 UTC, stewones commented
yo @bartacruz, can you check that conflicting file?

2022-10-04 13:50 UTC, bartacruz commented
Hi @stewones, it's done. Please let me know if there is anything else I can do

2022-10-05 21:23 UTC, stewones requested changes
thanks for the PR, it looks good to me just want to clarify the question above.

2022-10-05 21:23 UTC, stewones commented on android/src/main/java/com/getcapacitor/community/fcm/FCMPlugin.java
> +            data.put("token", tokenResult.getResult());
@bartacruz is this line really correct?

2022-10-05 21:23 UTC, stewones commented on android/src/main/java/com/getcapacitor/community/fcm/FCMPlugin.java
> +            data.put("token", tokenResult.getResult());
you're expecting `instanceIdResult` there's no `tokenResult` callback on this method

2024-02-20 14:25 UTC, stewones commented
almost 2 years now, closing due to inactivity.

2024-02-20 14:25 UTC, closed without merging